# Generated by Django 3.1.7 on 2021-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('anger', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('contempt', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('disgust', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('fear', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('happiness', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('neutral', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('sadness', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('surprise', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='7ddc96a5', max_length=8)),
                ('members', models.ManyToManyField(to='api.Client')),
            ],
        ),
    ]
