# Generated by Django 3.1.7 on 2021-03-28 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1b0ab8ee-406b-4d1d-95ea-95beae1a05bd')),
        ),
        migrations.AlterField(
            model_name='session',
            name='uuid',
            field=models.CharField(default='33d2440b', max_length=8),
        ),
    ]
